### ISSUE TITLE
关于提取模型的问题

### ISSUE THREAD

**Issue by Colorfulshadow** [Eikanya/Live2d-model#10]
关于提取模型的问题
![(✿◡‿◡)](https://cdn.jsdelivr.net/gh/colorfulshadowty1/img/img1/5NE}ILQ8[Y}B4{5G7VANZ$H.jpg
)</br>
不好意思啦，又来打扰您了，这次带来几个问题：</br>
- 请问下大佬的模型是怎么提取的，我想亲自体验一下哈哈哈
- 请问下大佬之后的模型都会是moc3格式吗，因为我之后为了避免版权问题可能会将moc3降级为moc
- 方便告知大佬的联系方式吗？网站，邮箱，QQ啥的都行(方便交流)（不方便当然也行啦）</br>
这么晚了打扰大佬了，最近不急，大佬慢慢回🎈</br>
![给花](https://cdn.jsdelivr.net/gh/colorfulshadowty1/img/img1/38648437.jpg)

**Comment by Eikanya** [comment]
模型提取一般是没有加密的手游和游戏，提取工具在https://www.perfare.net/有。手游模型一般都会有加密，图片声音之类。逆向的我也不太懂，靠网上提供的工具。
模型格式的话看游戏，新游戏一般都会使用moc3格式。

**Comment by Colorfulshadow** [comment]
嗯好的，我明天去试试，辛苦大佬了，早点睡哦～
