### ISSUE TITLE
关于圣剑战姬Sacred Sword princesses

### ISSUE THREAD

**Issue by VoIva** [Eikanya/Live2d-model#11]
dalao我想问一下 这个游戏怎么下载全部缓存？

**Comment by Eikanya** [comment]
自己爬服务器，可以看下方法[链接](https://eikanya.github.io/post/%E5%9C%A3%E5%89%91%E6%88%98%E5%A7%AC/)，还有就是下载xapk[链接](https://apkpure.com/sacred-sword-princesses/com.nutaku.eoa.enus.gp)。如果没用全部缓存就爬服务器吧

**Comment by Eikanya** [comment]
自己爬服务器，可以看下方法[链接](http://localhost:4000/post/%E5%9C%A3%E5%89%91%E6%88%98%E5%A7%AC/)，还有就是下载xapk[链接](https://apkpure.com/sacred-sword-princesses/com.nutaku.eoa.enus.gp)。看看index.txt文件记录和服务器上index.txt对比，如果没有全部缓存就爬服务器吧(应该就差一些CG)。

**Comment by Eikanya** [comment]
自己爬服务器，可以看下方法[链接](https://eikanya.github.io/post/%E5%9C%A3%E5%89%91%E6%88%98%E5%A7%AC/)，还有就是下载xapk[链接](https://apkpure.com/sacred-sword-princesses/com.nutaku.eoa.enus.gp)。看看index.txt文件记录和服务器上index.txt对比，如果没有全部缓存就爬服务器吧(应该就差一些CG)。

**Comment by VoIva** [comment]
好的谢谢dalao，我这就去试试。
