### ISSUE TITLE
时无瑕动作中手账上的字如何复原？

### ISSUE THREAD

**Issue by Yam0214** [Eikanya/Live2d-model#13]
直接改书本贴图倒是可以，不过live2dviewerEX的创意工坊里有人实现多种文字，请教一下如何实现？

还有，少女咖啡枪里个模型文件的动作文件是不是归类有些问题？发现了又角色在不同动作中长端不一的问题。

**Comment by Eikanya** [comment]
设置文本可以在live2dviewerEX设置动作文本，也可以改贴图，一般是设置一个动作再设置文本。添加多个动作就可以实现同一个动作实现多种文字。比如Mgirl09_lahudiejie_a.motion3.json你可以设置3个，然后每个显示不同的文本，调好时间轴，手动拉文本框。 改贴图的话也差不多，动作设置指令change_cos更换配置文件，就可以换贴图显示。
少女咖啡枪里模型是按照游戏的文件夹分类，一般按照活动归档。 角色动作不一样可能官方修改了这个模型的动作，更新了我没有把旧的删除。 你也可以自行提取游戏里live2d模型，提取方法参考https://www.perfare.net/

**Comment by Yam0214** [comment]
感谢指导。
1）请问动作文本指的是那种黑框白字的对话框吗？意思是把对话框拉到手账本的位置显示文本内容？这种效果可能不是非常好。
2）在您的启发下，我找到了replace_tex指令，可以直接替换贴图，应该可以实现不同动作上手账的文字。但会面临另一个问题，如Mgirl09_xiexiehuahua.motion3.json动作中出现了两个不同的文本，该方法只能显示其中一个文本贴图。
3）已经提取了live2d模型，确认了，官方的动作文件就是有这样的误差。手臂长短不一，可能在游戏中不连续出现也注意不到。已经通过修改motion3.json中Segments值解决。

**Comment by Yam0214** [comment]
感谢指导。
1）请问动作文本指的是那种黑框白字的对话框吗？意思是把对话框拉到手账本的位置显示文本内容？这种复原效果可能不是非常好，毕竟不像是白底黑字的手账文字。
2）在您的启发下，我找到了replace_tex指令，可以直接替换贴图，应该可以实现不同动作上手账的文字。但会面临另一个问题，如Mgirl09_xiexiehuahua.motion3.json动作中出现了两个不同的文本，该方法只能显示其中一个文本贴图。
3）已经提取了live2d模型，确认了，官方的动作文件就是有这样的误差。手臂长短不一，可能在游戏中不连续出现也注意不到。已经通过修改motion3.json中Segments值解决。

**Comment by Eikanya** [comment]
1. 如果想还原官方白底黑字的手账文字，应该是不可能，live2dviewerEX好像没有自定义文本框样式。
2. 如果直接修改贴图文字，就不需要在动作中配置文本。定义多个文本只能复制多张贴图，用指令随机显示不同的贴图。也就是说，每定义一个文本，就需要复制新的贴图，这样能是实现官方效果，但是多张贴图会造成模型体积过大问题。

**Comment by Yam0214** [comment]
嗯嗯，可惜动作指令只有两个触发阶段，一个在动作开始前，另一个在动作结束后。写写画画待机动作就没法还原了。

**Comment by Eikanya** [comment]
你可以测试一下动作配置进阶的上一个动作和下一个动作，应该是播放一个动作，再接着播放另一个动作。还有选择项可以设置。
