### ISSUE TITLE
炼铜学院的图片解密

### ISSUE THREAD

**Issue by totorowldox** [Eikanya/Live2d-model#14]
如题 怎么解密
**wtcl**

**Comment by totorowldox** [comment]
看得出来是用cocos2d做的

**Comment by Eikanya** [comment]
参考[魂器学院live2d提取](https://blog.tsundere.best/post/%E9%AD%82%E5%99%A8%E5%AD%A6%E9%99%A2/)/
sign:bogehcollege key:palmpi

**Comment by totorowldox** [comment]
谢谢 我搞定了
