### ISSUE TITLE
请问voice是哪一章的音频？

### ISSUE THREAD

**Issue by FXYANDDY** [Eikanya/Live2d-model#2]

**Comment by Eikanya** [comment]
音频没完全提取，建议自己去下载游戏，用GARbro提取。

**Comment by FXYANDDY** [comment]
谢谢，提取没有问题，硬盘容量告急，你能告诉我是哪一章的话，那就多谢了。

**Comment by FXYANDDY** [comment]
SCB文件存在大量乱码，有推荐的使用软件吗？我想提取live2dc对应的文本，毕竟live2d有文本与语音才更完善。今天用了几个小时处理，动作基本完成，但是文本与语音的处理并没有进展

**Comment by Eikanya** [comment]
你是问神楽黎明記吗，我也忘了是哪一章。解包可以参考https://blog.ztjal.info/

**Comment by FXYANDDY** [comment]
是的，谢谢

**Comment by FXYANDDY** [comment]
神楽黎明記～ちはやの章  3个live2d
神楽黎明記～奏の章      2个live2d
神楽黎明記～弥生の章～  2个live2d
神楽黎明記～なずなの章  4个live2d
神楽黎明記～紫の章～弐  3个live2d

以上是整理的数目，不知道对你有没有帮助

**Comment by Eikanya** [comment]
嗯，我没打算配置语音和文字。你需要的话可以自行配置。

**Comment by FXYANDDY** [comment]
个人觉得live2d没有文本与语音的话，是个严重的缺陷品。这游戏配置语音和文字，看来要不少时间去摸索了，还是玩这游戏的选择比较好

**Comment by FXYANDDY** [comment]
？
