### ISSUE TITLE
JSON syntax check

### ISSUE THREAD

**Issue by ghost** [Eikanya/Live2d-model#21]
Some JSON file comes with commas missing, which may cause parsing error in some web live2d engines like live2d-widget. 

https://github.com/Eikanya/Live2d-model/blob/c18353291d0e5d2b46ec75092c2dbb772381f29e/%E5%AE%9D%E7%9F%B3%E7%A0%94%E7%89%A9%E8%AF%AD/%E5%AE%9D%E7%9F%B3%E7%A0%94%E7%89%A9%E8%AF%AD/magelite/model.json#L7

Is it possible to run a syntax check on all json files in the repo?

**Comment by Eikanya** [comment]
ok
