### ISSUE TITLE
moc3 无法显示求助

### ISSUE THREAD

**Issue by hakanaku1234** [Eikanya/Live2d-model#22]
请问有碧蓝航线 demo page 原始码可参考吗 谢谢

(moc是正常的 不过moc 3无法显示)

**Comment by Eikanya** [comment]
live2d web区别moc和moc3。moc3显示可以参考我的github page

**Comment by hakanaku1234** [comment]
> live2d web区别moc和moc3。moc3显示可以参考我的github page

謝謝回覆 很有幫助 晚上來研究下 😙
