### ISSUE TITLE
有解包食物语的食魂模型吗

### ISSUE THREAD

**Issue by YYuanZhouLv** [Eikanya/Live2d-model#23]

**Comment by YYuanZhouLv** [comment]
如果有的话求增加，没有加密，纯unity解包

**Comment by viness14** [comment]
没有呢，大大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月12日(周一) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Eikanya/Live2d-model] 有解包食物语的食魂模型吗 (#23)




 
如果有的话求增加，没有加密，纯unity解包

**Comment by YYuanZhouLv** [comment]
好吧

**Comment by Eikanya** [comment]
食物语上传了，解包出来没有配置文件，需要自己配置，里面有个例子可以参考
