### ISSUE TITLE
挖坟——机动战队live2D

### ISSUE THREAD

**Issue by hfsztt** [Eikanya/Live2d-model#24]
很想要一些立绘的live2D材质包，比如教皇花嫁的live2D材质包
只要texture材质包就好
找了很多网站，也没找到机动战队具体怎么才能解出texture材质包，自己动手发现无从下手
很希望能看到能更新机动窑子的live2D材质包啊（哭）

**Comment by Eikanya** [comment]
没加密的话可以试试AssetStudio，live2d解包可以试试UnityLive2DExtractor，github上有开源下载

**Comment by hfsztt** [comment]
机动战队这个游戏不论是从模拟器里，还是物理的手机上，都找不到游戏安装目录是什么，即便是obb文件夹下有jdzd，里面也是空空如也，完全没法解包啊

**Comment by Eikanya** [comment]
下载完整安装包，解压就有了

**Comment by hfsztt** [comment]
我下载了xpak格式的安装包，下面有一个obb文件，但这个obb文件很诡异，有一个多G的容量，用zip压缩文件拆或者用其它工具拆，都只能拆出10几M的文件，且几乎都没用

**Comment by Eikanya** [comment]
那就下个安卓模拟器，root了就能从文件夹里提取文件

**Comment by hfsztt** [comment]
所有的文件我都能看见了，都是一堆*.enc格式的文件，用assetstudio, garbro之类的工具无法打开

**Comment by hfsztt** [comment]
我把文件样本发上来了，zip文件里面就是我说的enc文件，工工整整的1MB大小
[ex.image.siluokayihuajia.zip](https://github.com/Eikanya/Live2d-model/files/6323731/ex.image.siluokayihuajia.zip)

**Comment by Eikanya** [comment]
加密过的，我不会解密
