### ISSUE TITLE
大佬，能改一下文件名吗，单个文件下载没法走中文路径

### ISSUE THREAD

**Issue by ouroborosscr** [Eikanya/Live2d-model#25]

**Comment by ZaiDuoYiDian** [comment]
欧式保存的别个大佬的资源库啊，你自己保存在你的github仓库里嘛，然后自己改了下吧

ouroborosscr ***@***.***> 於 2021年5月19日 週三 上午3:10寫道：

**Comment by Eikanya** [comment]
可以使用GitZip下载单个文件夹
