### ISSUE TITLE
个人觉得live2d没有文本与语音的话，是个严重的缺陷品。这游戏配置语音和文字，看来要不少时间去摸索了，还是玩这游戏的选择比较好

### ISSUE THREAD

**Issue by FXYANDDY** [Eikanya/Live2d-model#3]
个人觉得live2d没有文本与语音的话，是个严重的缺陷品。这游戏配置语音和文字，看来要不少时间去摸索了，还是玩这游戏的选择比较好？

_Originally posted by @FXYANDDY in https://github.com/Eikanya/Live2d-model/issues/2#issuecomment-538749524_

**Comment by Eikanya** [comment]
你想配置live2d，可以试试少女前线的模型，有音频有文字，在萌娘百科里。

**Comment by FXYANDDY** [comment]
推荐来live2dhub.com，在那里有2个我发表的模型。或许我没有玩这些游戏吧，感觉少了点什么。

**Comment by FXYANDDY** [comment]
奏の章，v106a、w101a两个模型已完成动作、全台词及文本的配置，s_kanade01的台词及文本没有进展。（我也应该暂时离开live2d ）

**Comment by Eikanya** [comment]
嗯，如果有时间还是玩玩Live2D Cubism，自己制作模型
