### ISSUE TITLE
关于moc和moc3格式的问题

### ISSUE THREAD

**Issue by Alecition** [Eikanya/Live2d-model#30]
大佬你好，我像问一下这两种格式的区别是什么，还有就是比如像prprlive和vts之类的软件无法加载moc模型，但是可以加载moc3模型，想问一下有方法吧moc模型转换为moc3吗，网上搜了一圈都没找到相关问题，不知道是不是我的问题比较愚蠢X﹏X求大佬解答

**Comment by Eikanya** [comment]
moc是live2d旧版本的格式，moc3是live2d新版本的格式。一般是不支持moc转换moc3，只能从源工程文件转换输出moc3

**Comment by Alecition** [comment]
一般来说不应该兼容一下旧的嘛，所以说现在旧版本的moc就无法用vts之类的加载了嘛？那么大佬提取的一些旧版本live2d是无法用于面捕了是嘛？

**Comment by Alecition** [comment]
用了大佬推荐的live2dviewerEX，这软件moc和moc3模型都能打开，非常不错，虚拟摄像头使用要设置一下分辨率，开发者都有教程，问题解决。感谢Eikanya大佬的博客！！！

**Comment by ZaiDuoYiDian** [comment]
可以解下《解神者》嘛，那个朱雀蛮蛮好看的

Eikan ***@***.***> 於 2021年9月26日 週日 下午3:06寫道：

**Comment by Eikanya** [comment]
加密的模型不会解密
