### ISSUE TITLE
hexo上不显示

### ISSUE THREAD

**Issue by fengdongliuxiang** [Eikanya/Live2d-model#31]
用的hexo-helper-live2d插件
站点配置如下：
live2d:
  enable: true
  pluginModelPath: assets/
  model:
    use: aidang-2  #模板目录，在node_modules里
  display:
    position: right
    width: 300
    height: 600
  mobile:
    show: false  #是否在手机进行显示

model文件路径：C:\Users\Administrator\blog\node_modules\aidang-2\assets，我手动给它加了个assets文件夹，文件名中_改成了-

**Comment by Eikanya** [comment]
应该是路径问题，看看官方插件的配置。还有F12看看报错什么。

**Comment by fengdongliuxiang** [comment]
我看了hexo-helper-live2d的issue，发现了相同的情况，应该是暂时不支持这类模型

**Comment by Eikanya** [comment]
这个插件只支持moc,不支持moc3.如果你要放碧蓝航线的live2d，我可以参考一下我的github的blog里的js，下载源码看看吧

**Comment by fengdongliuxiang** [comment]
> 这个插件只支持moc,不支持moc3.如果你要放碧蓝航线的live2d，我可以参考一下我的github的blog里的js，下载源码看看吧

好的，谢谢
