### ISSUE TITLE
如何调整博客上live2d 的 css

### ISSUE THREAD

**Issue by hhdqirui** [Eikanya/Live2d-model#32]
感谢大佬的一系列代码！想问一下在哪里去改博客上的live2d 的 css，因为部分live2d显示不完整。感谢！

**Comment by Eikanya** [comment]
live2d显示不完整应该修改loadModel.js文件的参数。如果你是用我博客的live2d的源码，loadModel.js在live2dv3的文件里面。

**Comment by hhdqirui** [comment]
问题解决！感谢！
