### ISSUE TITLE
食物语

### ISSUE THREAD

**Issue by YYuanZhouLv** [Eikanya/Live2d-model#35]
求更下新模型

**Comment by Eikanya** [comment]
自己提取也可以的，这游戏live2d没有加密

**Comment by YYuanZhouLv** [comment]
但我看里面是单独文件的那种，只能一个文件一个文件那种提取，很麻烦，有没有什么软件可以批量解包啊

**Comment by YYuanZhouLv** [comment]
用过个解包的，选整个文件夹会因为什么重名报错，导致只能两三个文件夹一起搞进去解

**Comment by Eikanya** [comment]
AssetStudio可以，提取前设置按照文件夹提取

**Comment by YYuanZhouLv** [comment]
哦，谢谢，我试试
