### ISSUE TITLE
girl cafe gun live2ds

### ISSUE THREAD

**Issue by vkt133** [Eikanya/Live2d-model#36]
i tried using unitylive2dextractor on the folders and i got a outofmemoryexception error... how did you extract them?

**Comment by Eikanya** [comment]
try this [UnityLive2DExtractor+for+ガール・カフェ・ガン](https://github.com/Eikanya/Live2d-model/blob/master/%E5%B0%91%E5%A5%B3%E5%92%96%E5%95%A1%E6%9E%AA%20girls%20cafe%20gun/UnityLive2DExtractor%2Bfor%2B%E3%82%AC%E3%83%BC%E3%83%AB%E3%83%BB%E3%82%AB%E3%83%95%E3%82%A7%E3%83%BB%E3%82%AC%E3%83%B3.zip)

**Comment by vkt133** [comment]
well... thank you, it managed to extract what i need... mostly.. theres a file that somehow still gave out an error, specifically an argumentoutofexception error, any ideas how to solve this?

**Comment by Eikanya** [comment]
sorry,no idea,
