### ISSUE TITLE
食物語live2d拆包出來後面有.prefab 有時候又有.dat

### ISSUE THREAD

**Issue by kyliemama** [Eikanya/Live2d-model#37]
請問大佬是用什麽軟件去掉的 還是我前面有些步驟做錯了 感謝大佬
![image](https://user-images.githubusercontent.com/103545052/196577533-1d6071a9-73e1-4304-bb03-7dca8c19d1ae.png)
![image](https://user-images.githubusercontent.com/103545052/196577565-9881b4aa-5ad1-4a72-9609-4cccab3ddc37.png)

**Comment by Eikanya** [comment]
你在AssetStudio设置显示文件路径，然后按照文件路径提取。这样会分开文件夹了
