### ISSUE TITLE
下载不了

### ISSUE THREAD

**Issue by DrLimomo** [Eikanya/Live2d-model#39]
我使用了简介中的插件，但仍旧无法下载，我使用Git ZIP时下载的文件全都是损坏的，直接下载又会出现22B的空压缩包

**Comment by Eikanya** [comment]
试试DownGit，https://minhaskamal.github.io/DownGit/#/home

**Comment by DrLimomo** [comment]
有更快的方法吗，这程序的下载速度好慢，只有（平均速度）68kb/s

**Comment by DrLimomo** [comment]
还有就是能不能搞个百度网盘或者阿里云盘，这样国内会方便一点

**Comment by DrLimomo** [comment]
> 试试DownGit，https://minhaskamal.github.io/DownGit/#/home
还有其他办法吗？

**Comment by Eikanya** [comment]
没上传网盘，慢的话开代理下载吧

**Comment by DrLimomo** [comment]
不行，仍然是一个320MB的损坏压缩包

**Comment by Eikanya** [comment]
那只能用git的sparsecheckout命令，可以单选拉取一个文件夹。

**Comment by DrLimomo** [comment]
> 那只能用git的sparsecheckout命令，可以单选拉取一个文件夹。

怎么操作呢？

**Comment by DrLimomo** [comment]
目前问题貌似是解决了，但仍有不太好的地方，DownGit的下载慢且容易失败（文件损坏）
