### ISSUE TITLE
无法直接适配，没有语音不能动。想学，想适配，有方法吗？

### ISSUE THREAD

**Issue by wenyaolinxi** [Eikanya/Live2d-model#4]

**Comment by Eikanya** [comment]
你用什么软件配置live2d？建议看一下软件的官方文档。.json文件是配置文件，不可以参考一下怎么配置的。

**Comment by wenyaolinxi** [comment]
live2dviverEX的手机版。主要模型是可以加载的啦(￣▽￣)，也会跟着手动ｸﾞｯ!(๑•̀ㅂ•́)و✧，但是点着没有反应∑(￣□￣)，明明文件里有看到的语音文件和动作文件的(๑ó﹏ò๑)。故此来问问(ʃƪ ˘ ³˘)

**Comment by Eikanya** [comment]
你live2dviewerEX看看电脑版怎么样？触摸的话你需要先设置触摸地方，再去motion里设置触摸地方的动作，比如触摸头taphead。如果单单是设置tap，可能不会触发动作。

**Comment by wenyaolinxi** [comment]
哦哦，是要写触摸代码吗('◇'｀)。方便告知怎么写吗？

**Comment by Eikanya** [comment]
不需要，你在steam买live2dviewerEX。参照官方文档配置就行了，不懂再问吧

**Comment by wenyaolinxi** [comment]
嗯嗯，谢谢大佬。
