### ISSUE TITLE
[FEATURE REQUEST] Support for steam vtube

### ISSUE THREAD

**Issue by MarcWebber** [Eikanya/Live2d-model#41]
导入steam vtube之后所有的模型加载后都是空白。无法预览也没有任何动作。
请问如何将这些模型正确导入vtube？
同时想问一下作者是否有做vtube的适配打算？

**Comment by Eikanya** [comment]
配置不兼容吧，你要看vtube官方的配置方式，不是单单导入confin.json就行的。
