### ISSUE TITLE
为什么没办法导出音频啊

### ISSUE THREAD

**Issue by totorowldox** [Eikanya/Live2d-model#6]
为什么我吧.bnk拖到bnkextr.exe上没有用啊
![image](https://user-images.githubusercontent.com/58592575/70317458-c20c5c00-1858-11ea-9337-e0e740c831db.png)

**Comment by totorowldox** [comment]
`Wwise *.BNK File Extractor
(c) CTPAX-X Team 2009-2010 - http://www.CTPAX-X.org
(c) RAWR 2015 - http://www.rawr4firefall.com`
出来这串东西

**Comment by totorowldox** [comment]
在线等 急

**Comment by Eikanya** [comment]
bnk文件直接拖到bnkextr.exe就能导出.wbm文件了。你的Vo_Normal_Girl_07.bnk文件有多大？我这个是725KB，能正常导出。

**Comment by totorowldox** [comment]
给一下吧 我这个太小了啊 只有8K啊(手动滑稽)

**Comment by totorowldox** [comment]
难受啊》

**Comment by Eikanya** [comment]
嗯 有点麻烦，太小的话没有语音的。我也是遇到这个问题

**Comment by totorowldox** [comment]
加q2553658033给我一下呗

**Comment by totorowldox** [comment]
要么q号给我 我加你

**Comment by Eikanya** [comment]
我的语音文件也不全，将就吧。我上传git了

**Comment by totorowldox** [comment]
谢谢啊

**Comment by Eikanya** [comment]
音频找到方法提取了，详细有看我的博客，只要使用fiddle抓包找到地址，换个后缀就能下载全部音频
