### ISSUE TITLE
双生视界新版命名文件已经不能用perfare的提取工具正常解压了

### ISSUE THREAD

**Issue by magickurmi** [Eikanya/Live2d-model#7]
大佬您好，我是最近才接触的Live2DViewerEX文件并且顺利制作了艾琳了两款l2d作品，但是在年后版本中，新命名的文件比如战术装备三期朱诺老师伊珂丝小真开头均是tw15__l2d命名的，在perfare作者的 https://www.perfare.net/1564.html 下也有其他人看到问题了，都是无法解压u文件。
想问问大佬解决的办法，顺便已经看到您上传的以tw和xin开头的文件了，询问一下如何下载

**Comment by Eikanya** [comment]
可以吧，只是tw75__l2d_231的动作文件报错。解压u文件要放在文件夹里，拉文件夹解压。

**Comment by magickurmi** [comment]
感谢大佬深夜回复，请问怎么下载您在网页上传的那些文件，拜师拜师

**Comment by Eikanya** [comment]
主项目，右上点击clone or download

**Comment by magickurmi** [comment]
好的谢谢，麻烦了
