### ISSUE TITLE
关于版权问题

### ISSUE THREAD

**Issue by Colorfulshadow** [Eikanya/Live2d-model#8]
你好，我很喜欢你所收集的live2d模型！

现在，我已经将部分live2d模型剔除，筛选了部分模型并修补了部分模型的json，准备以 GPLv3的方式进行再发布，并给需要的朋友以提供帮助，希望获取你的同意

> 联系方式：colorfulshadowty@gmail.com

> 示例:https://blog.oyi.me

Thanks♪(･ω･)ﾉ

**Comment by Eikanya** [comment]
不好意思，没有看到你的issue。我很乐意你能使用是收集的模型，使用的话你需要自行配置json(因为我都没有配置好)。我也很希望我收集的live2d模型能让大家使用。

**Comment by Colorfulshadow** [comment]
啊谢谢大佬，我会时常关注你发布的模型的，另外你的模型我已配置好json，大佬可以看一看，就在我的github里QWQ，里面有加上你的Github
ヾ(≧▽≦*)o

**Comment by Eikanya** [comment]
模型很多都是提取游戏里面的，全部模型配置好json比较麻烦，其实也不难。我建议还是自己来配置。
moc3模型我看过https://himehane.club/live2d_on_website/这个博客实现，你可以研究一下。

**Comment by Colorfulshadow** [comment]
嗯好的，谢谢你哦~
