### ISSUE TITLE
请问有机动战队(Iron Saga)的live2d提取方法么？

### ISSUE THREAD

**Issue by DancingGhost** [Eikanya/Live2d-model#9]
大佬好！

个人感觉《机动战队》这个游戏里一些live2d还挺好看的，就想提取出来丢到桌面当背景。然而各种方法试过了之后发现无法解密文件。

首先找了apk包，解包之后有一个live2d的folder，但是只有四个文件，明显不太对，然后在texture的文件夹里找到了很多*.enc，查了查压缩前后的大小，应该就是这些了。然而这个加密并不知道怎么解……文件夹里还有一个desc.txt文件，里面包含了很多类似
section ex.image.yilaienzhanli ### ### #######
sp driverAsset/ex.image.yilaienzhanli -### -### ### # # #### （#是数字）
的内容，估计可能和decode有关？

之后在模拟器里安装了eng服，国服，台服几个版本，发现内容几乎差不多就是这样，除了*.enc文件，没找到其他大批量和游戏人物有关的文件。

请问大佬有什么思路提取这种live2d么？或者我的思路从开始就是错的？

感谢！

**Comment by Eikanya** [comment]
其实动作人物不一定是live2d模型，有可能是普通的动作animation，有动作不一定是live2d。我看过dese.txt，只是图片合作的动作。

**Comment by DancingGhost** [comment]
我看了下文件，貌似所有的游戏特效也包含在一起，比如爆炸，导弹飞行之类的
大部分这种effect类的东西，每一类都会有很多行“名字@一串数字”这种格式，貌似这个肯定是图片合作的动作

如果是人物的话，比如伊莱恩的某一款皮肤，就只有两行
section ex.image.yilaienzhanli ### ### #######
sp driverAsset/ex.image.yilaienzhanli -### -### ### # # #### 
这种格式，也是图片合作的动作么？

**Comment by Eikanya** [comment]
应该吧，图片打开角色部位是拆分的，dese.txt是合成部位位置，你可以看看akp的assets/spine文件夹，json是动作配置文件。

**Comment by DancingGhost** [comment]
哎？图片可以打开么？我现在就发愁打不开图片，如果能的话，理论上我可以想办法拼起来。
Json文件我看过了，是和正常的live2d的json配置不太一样，有点像mtn文件……

**Comment by Eikanya** [comment]
解密能打开，找相关工具吧，知道游戏引擎就提取就简单(应该不是untiy)。atlas是图片合成位置文件，json是动作配置文件，enc应该是图片文件。图片提取出来找相关合成工具能拼合起来，不过我对这方面没怎么研究。

**Comment by DancingGhost** [comment]
图片拼接我可以写，就是解密比较发愁，我再查查相关资料吧，多谢大佬指路

**Comment by Eikanya** [comment]
游戏是用adobe air做的，你查这方面资料吧。
